from __future__ import annotations

"""Application disclaimer and notice text.

These strings provide context for findings and explanations generated by the system.
"""


AUDIT_ONLY_NOTICE = (
	"This system audits clinical data integrity and does not diagnose, prescribe, or provide medical advice. "
	"Findings describe data-integrity conditions established by deterministic rules."
)

AI_AUDIT_ONLY_DISCLAIMER = (
	"AI-generated explanation. This output is non-diagnostic and non-prescriptive; "
	"it requires human review before any action is taken. "
	"The contradiction was established by deterministic rule evaluation; AI text provides explanation and confidence context."
)

RESOLUTION_AUDIT_ONLY_NOTE = (
	"This draft requires human review and approval before any action is taken."
)
